[tool.poetry]
name = "breakage-rate-model"
version = "0.6.5"
description = "Models and utilities for fitting breakage energy-rate relationships."
authors = ["HR94 <haoran.ji@kit.edu>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "breakage_rate_model", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^2.3.5"
scipy = "^1.16.3"
matplotlib = "^3.10.8"
torch = "^2.9.1"
h5py = "^3.15.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
