[tool.poetry]
name = "lmc"
version = "0.7.0"
description = "Lattice Monte Carlo (LMC) simulator for agglomerate fracture and fragment analysis."
authors = ["HR94 <haoran.ji@kit.edu>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "lmc", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^2.3.5"
numba = "^0.63.1"
matplotlib = "^3.10.8"
h5py = "^3.15.1"
lmdb = "^1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
