[tool.poetry]
name = "pbe-optimizer"
version = "0.7.0"
description = "Optimization framework for PBE solvers with adapter-based backend integration."
authors = ["HR94 <haoran.ji@kit.edu>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    { include = "pbe_optimizer", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^2.3.5"
pandas = "^2.3.3"
scipy = "^1.16.3"
scikit-learn = "^1.8.0"
matplotlib = "^3.10.8"
yappi = "^1.7.3"
torch = "^2.9.1"
h5py = "^3.15.1"
optuna = "^4.6.0"
cmaes = "^0.12.0"
ray = {extras = ["default,train,tune"], version = "^2.52.1"}
filelock = "^3.19.1"
pbe-core = "^0.7"
dpbe = "^0.7"
mcpbe = "^0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
